Revert to regular setup and run commands.

diff --git a/dnn.yaml b/dnn.yaml
--- a/dnn.yaml
+++ b/dnn.yaml
@@ -20,32 +20,24 @@ file_mounts:
     source: s3://dagster-skypilot-bucket
     mode: MOUNT
 
-# setup: |
-#   set -e  # Exit if any command failed.
-#   git clone https://github.com/huggingface/transformers/ || true
-#   cd transformers
-#   pip install .
-#   cd examples/pytorch/text-classification
-#   pip install -r requirements.txt
-
-# run: |
-#   set -e  # Exit if any command failed.
-#   cd transformers/examples/pytorch/text-classification
-#   python run_glue.py \
-#     --model_name_or_path bert-base-cased \
-#     --dataset_name imdb  \
-#     --do_train \
-#     --max_seq_length 128 \
-#     --per_device_train_batch_size 32 \
-#     --learning_rate 2e-5 \
-#     --max_steps 50 \
-#     --output_dir /tmp/imdb/ --overwrite_output_dir \
-#     --fp16
-
 setup: |
-  set -e
-  echo "Running setup command."
+  set -e  # Exit if any command failed.
+  git clone https://github.com/huggingface/transformers/ || true
+  cd transformers
+  pip install .
+  cd examples/pytorch/text-classification
+  pip install -r requirements.txt
 
 run: |
-  set -e
-  echo "Running run command."
+  set -e  # Exit if any command failed.
+  cd transformers/examples/pytorch/text-classification
+  python run_glue.py \
+    --model_name_or_path bert-base-cased \
+    --dataset_name imdb  \
+    --do_train \
+    --max_seq_length 128 \
+    --per_device_train_batch_size 32 \
+    --learning_rate 2e-5 \
+    --max_steps 50 \
+    --output_dir /tmp/imdb/ --overwrite_output_dir \
+    --fp16
